# Define the game tree as an adjacency list
# game_tree_graph = {
#     "A": {'value': 0, 'children': ["B", "C", "D"]},
#     "B": {'value': 0, 'children': ["E", "F"]},
#     "C": {'value': 0, 'children': ["G", "H", "J"]},
#     "D": {'value': 0, 'children': ["K", "L", "M"]},
#     "E": {'value': 0, 'children': ["E1", "E2"]},
#     "E1": {'value': 2, 'children': []},
#     "E2": {'value': 5, 'children': []},
#     "F": {'value': 0, 'children': ["F1", "F2"]},
#     "F1": {'value': 7, 'children': []},
#     "F2": {'value': 10, 'children': []},
#     "G": {'value': 0, 'children': ["G1", "G2", "G3"]},
#     "G1": {'value': 10, 'children': []},
#     "G2": {'value': 11, 'children': []},
#     "G3": {'value': 15, 'children': []},
#     "H": {'value': 0, 'children': ["H1"]},
#     "H1": {'value': 2, 'children': []},
#     "J": {'value': 0, 'children': ["J1", "J2"]},
#     "J1": {'value': 6, 'children': []},
#     "J2": {'value': 8, 'children': []},
#     "K": {'value': 0, 'children': ["K1"]},
#     "K1": {'value': 4, 'children': []},
#     "L": {'value': 0, 'children': ["L1", "L2"]},
#     "L1": {'value': 4, 'children': []},
#     "L2": {'value': 3, 'children': []},
#     "M": {'value': 0, 'children': ["M1", "M2"]},
#     "M1": {'value': 5, 'children': []},
#     "M2": {'value': 10, 'children': []},
# }

game_tree_graph = {
    "A": {'value': 0, 'children': ["B", "C", "D"]},
    "B": {'value': 0, 'children': ["B1", "B2"]},
    "B1": {'value': 5, 'children': []},
    "B2": {'value': 17, 'children': []},
    "C": {'value': 0, 'children': ["E", "C1", "C2"]},
    "C1": {'value': 4, 'children': []},
    "C2": {'value': 6, 'children': []},
    "D": {'value': 0, 'children': ["F", "D1", "D2"]},
    "D1": {'value': 5, 'children': []},
    "D2": {'value': -1, 'children': []},
    "E": {'value': 0, 'children': ["G", "E1"]},
    "E1": {'value': 2, 'children': []},
    "G": {'value': 0, 'children': ["G1", "G2"]},
    "G1": {'value': 3, 'children': []},
    "G2": {'value': 8, 'children': []},
    "F": {'value': 0, 'children': ["F1", "F2", "F3"]},
    "F1": {'value': 12, 'children': []},
    "F2": {'value': 4, 'children': []},
    "F3": {'value': -2, 'children': []},
}